spring:
  datasource:
    url: jdbc:h2:mem:appdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      engine: ""
      charset: ""
      json_type: "VARCHAR(4000)"
      updated_at_on_update: "DEFAULT CURRENT_TIMESTAMP"
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  payment:
    url:
      success: "http://localhost:8080/payments/success"
      fail: "http://localhost:8080/payments/fail"
      cancel: "http://localhost:8080/payments/cancel"